### PR TITLE
Add extensive example of Hydra API Documentation creation 

### LINKED ISSUE #16: Add Extensive Example for hydrus Workflow
As in https://github.com/HTTP-APIs/documentation-hydrus/issues/6

---
As `hydrus` define a precise workflow like:

1. the API designer write a SWAGGER/OpenAPI JSON document that describes his/her API (yet to be implemented, hopefully this year. Please consider submitting an application for this)
2. `hydrus` parser will parse this JSON into a HYDRA API documentation ([example here](https://github.com/HTTP-APIs/hydra-flock-vocab/blob/master/hydra_flock.jsonld)) 
3. `hydrus` deploys the Web server byt parsing the outcome at 2.
4. `hydrus` serves the API
5. HYDRA-aware generic clients can use the API

We need an extensive document that improve the current WIKI by adding a detailed description of this workflow, with references to RDF codebase and Hydra draft.

References:
* [URSA](http://alien-mcl.github.io/URSA/doc.html)
---

### PR DESCRIPTION
**Pull request by vddesai1998**
Fixes #16

### CODE REVIEW

**Comment by Mec-iS** [comment]
If you have taken something from Markus' text, you should reference the source at the end of the file.

**Comment by vddesai1998** [comment]
Totally forgot that..! Thanks for pointing out

**Comment by vddesai1998** [comment]
Gave the credits and included a link to the source.

**Comment by Mec-iS** [comment]
Try also to read the [new version of the database design document](https://github.com/HTTP-APIs/hydra-ecosystem-wiki/blob/master/Design.md), maybe you can find something to add.

**Comment by vddesai1998** [comment]
Does it qualify as CAC (Class -> Property -> Class) or IAC ( Resource -> Property -> Class)?
Can't it be both?
```
"property": {
                        "@id": "vocab:EntryPoint/Area",
                        "@type": "hydra:Link",
                        "description": "Class for Area of Interest of the server",
                        "domain": "vocab:EntryPoint",
                        "label": "Area",
                        "range": "vocab:Area",
```

**Comment by Mec-iS** [comment]
I cannot understand the context from this chunck. Please provide a link to the lines.

**Pull request merged**
